---
.travis.yml:
  secure: "DDZZtZOEb7mqD81bNzEIQC8FrSIRPO0R0nrPkDGj7E1P1Pr/uhgOVVg58A6bPjsqUPLE7arscf2TtRT9cuqfoZP3bhy/g7j+0w6QnAt1f6bPQ9zNL0sgOGEM1rS2WIjRdkFSFcM/kNtrVRhrYEKgv/vOferkUundP+IRCx5HDnU="
#spec/spec_helper_acceptance.rb:
# Temporarily unmanage spec_helper_acceptance (iss. #133)
#  windows: true
#  dependencies:
#    - puppetlabs-stdlib
#    - puppetlabs-powershell
